apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: operation-applications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: argocd,operation-applications,traefik
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'