apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.2/manifests/install.yaml

# additional resources like ingress rules, cluster and repository secrets.
#resources:

# changes to config maps
#patchesStrategicMerge:
#- overlays/argo-cd-cm.yaml

namespace: argocd