apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-config
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/tkohn/homelab-k8s-apps.git
    path: operation-applications/argo-cd-config
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true