apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: operation-applications
  source:
    repoURL: https://github.com/tkohn/homelab-k8s-apps.git
    path: operation-applications/argocd-config
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true